package com.wsms.entity;

public enum ServerStatus {
    ACTIVE, //AGENT - SEND DATA
    INACTIVE, //AGENT - DIDNOT SEND DATA
    UNKNOWN, // AGENT - NEVER SEND DATA, WHEN OUR AGENT IS DOWN - WE CAN NOT DETERMINE IF SERVER IS UP OR DOWN
    WARNING, // AGENT - DID NOT SEND DATA IN 15S
    
    // REMOVED WARNING, ERROR, BLOCKED TYPE - AS of these are server health field
}

