services:
  - type: web
    name: wsms-backend
    runtime: docker
    plan: free
    rootDir: backend/wsms
    autoDeploy: true
    envVars:
      - key: APP_BACKEND_URL
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
