spring.application.name=wsms
spring.datasource.url=jdbc:postgresql://localhost:5432/wsms
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=Q29kZXhXU01TX0pXVF9TRUNSRVRfS0VZX0ZPUl9IUzI1Nl9NVVNUX0JFX0xPTkdfRU5PVUdIXzIwMjY=
app.jwt.expiration-ms=86400000
spring.devtools.restart.enabled=true
app.cors.allowed-origins=http://localhost:5173,http://localhost:5177,http://127.0.0.1:5173,http://127.0.0.1:5177
