spring.application.name=wsms
spring.datasource.url=jdbc:mysql://localhost:3306/wsms_test
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.jwt.secret=Q29kZXhXU01TX0pXVF9TRUNSRVRfS0VZX0ZPUl9IUzI1Nl9NVVNUX0JFX0xPTkdfRU5PVUdIXzIwMjY=
app.jwt.expiration-ms=86400000
spring.devtools.restart.enabled=true
app.cors.allowed-origins=http://localhost:5173,http://localhost:5177,http://127.0.0.1:5173,http://127.0.0.1:5177,http://localhost:4017
app.terminal.shell=

# Metric data retention configuration
# How many days to keep metrics before automatic cleanup (default: 30 days)
app.metrics.retention-days=30

# Enable scheduled tasks
spring.task.scheduling.enabled=true

app.agent.jar-url=https://wsms-s3.s3.eu-north-1.amazonaws.com/${app.agent.jar-name}

#this smtp cofiguration are in application-secret.properties
spring.config.import=optional:classpath:application-secret.properties

#backend-url
#app.backend.url=http://localhost:8080
app.backend.url=https://0qn5hjj7-8080.inc1.devtunnels.ms
app.agent.jar-name=server-agent-v4.0.2.jar

#JPA config
spring.jpa.show-sql=false
logging.level.org.hibernate=ERROR

#app.config
app.config.allow-web-client-requests=true
app.config.show-terminal-on-server-setup=true