
# Password reset email configuration
# Set app.mail.enabled=true and configure spring.mail.* settings to send emails for OTP.
app.mail.enabled=true
app.mail.from=no-reply@example.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=praveen.panchanathan03@gmail.com
spring.mail.password=ziyb bvuf lviu vxdj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
